--Landline join - DataTrust
SELECT COUNT (DISTINCT VOTER_TELEPHONES_LANDLINE_UNFORMATTED)
FROM SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST dt
LEFT JOIN SAMPLE_PLUS.VOTER_DATA.L2_POLITICAL_OPTIMUS__US__2022_02_12 l2
WHERE CONCAT(dt.LANDLINE_AREACODE, dt.LANDLINE_NUMBER) = l2.VOTER_TELEPHONES_LANDLINE_UNFORMATTED

--Cell join - DataTrust
SELECT COUNT (DISTINCT VOTER_TELEPHONES_CELL_PHONE_UNFORMATTED)
FROM SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST dt
LEFT JOIN SAMPLE_PLUS.VOTER_DATA.L2_POLITICAL_OPTIMUS__US__2022_02_12 l2
WHERE CONCAT(dt.CELLPHONE_AREACODE, dt.CELLPHONE_NUMBER) = l2.VOTER_TELEPHONES_CELL_PHONE_UNFORMATTED

SELECT * 
FROM SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST
WHERE DT_REGID LIKE '%0440D927-D20D-4796-BEA8-73CF95A633E4%'
LIMIT 1000;


COPY INTO 'gcs://rainier-dev/unload/datatrust_unload'
FROM (
  SELECT 
      DT_ID,
      DT_REGID,
      STATEVOTERID,
      FIRSTNAME,
      LASTNAME,
      DMA,
      LANDLINE_AREACODE,
      LANDLINE_NUMBER,
      CELLPHONE_AREACODE,
      CELLPHONE_NUMBER,
      REGISTRATIONADDRESSZIP5
  FROM SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST
)
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
HEADER = TRUE
OVERWRITE = TRUE
STORAGE_INTEGRATION = RAINIER_ML_DEV;



--Landline anti-join - DataTrust (in L2 but not in DataTrust)
SELECT COUNT (DISTINCT VOTER_TELEPHONES_LANDLINE_UNFORMATTED)
FROM SAMPLE_PLUS.VOTER_DATA.L2_POLITICAL_OPTIMUS__US__2022_02_12 l2 
LEFT JOIN SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST dt on CONCAT(dt.LANDLINE_AREACODE, dt.LANDLINE_NUMBER) = l2.VOTER_TELEPHONES_LANDLINE_UNFORMATTED
WHERE dt.DT_REGID is null

--Cell anti-join - DataTrust (in L2 but not in DataTrust)
SELECT COUNT (DISTINCT VOTER_TELEPHONES_CELL_PHONE_UNFORMATTED)
FROM SAMPLE_PLUS.VOTER_DATA.L2_POLITICAL_OPTIMUS__US__2022_02_12 l2 
LEFT JOIN SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST dt on CONCAT(dt.CELLPHONE_AREACODE, dt.CELLPHONE_NUMBER) = l2.VOTER_TELEPHONES_CELL_PHONE_UNFORMATTED
WHERE dt.DT_REGID is null

--Landline anti-join - DataTrust (in DataTrust but not in L2)
SELECT COUNT (DISTINCT CONCAT(dt.LANDLINE_AREACODE, dt.LANDLINE_NUMBER))
FROM SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST dt 
LEFT JOIN SAMPLE_PLUS.VOTER_DATA.L2_POLITICAL_OPTIMUS__US__2022_02_12 l2 on CONCAT(dt.LANDLINE_AREACODE, dt.LANDLINE_NUMBER) = l2.VOTER_TELEPHONES_LANDLINE_UNFORMATTED
WHERE l2.LALVOTERID is null

--Cell anti-join - DataTrust (in DataTrust but not in L2)
SELECT COUNT (DISTINCT CONCAT(dt.CELLPHONE_AREACODE, dt.CELLPHONE_NUMBER))
FROM SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST dt  
LEFT JOIN SAMPLE_PLUS.VOTER_DATA.L2_POLITICAL_OPTIMUS__US__2022_02_12 l2 on CONCAT(dt.CELLPHONE_AREACODE, dt.CELLPHONE_NUMBER) = l2.VOTER_TELEPHONES_CELL_PHONE_UNFORMATTED
WHERE l2.LALVOTERID is null



SELECT count(distinct CONCAT(dt.CELLPHONE_AREACODE, dt.CELLPHONE_NUMBER))
FROM SAMPLE_PLUS.VOTER_DATA.DATATRUST_INGEST dt 

--TARGETSMART, CATALIST, AND ARISTOTLE DO NOT HAVE PHONE NUMBERS






